services:
  api:
    profiles: [ "api" ]
    container_name: domegym.gym_management_api
    image: domegym.gym_management_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "8000"
    ports:
      - "${GYM_MANAGEMENT_UVICORN__PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      postgres_migration:
        condition: service_completed_successfully
    networks:
      - domegym.network
    volumes:
      - ./.env:/app/.env:ro
    environment:
      GYM_MANAGEMENT_DATABASE__HOST: domegym.postgres
      GYM_MANAGEMENT_RABBITMQ__HOST: domegym.rabbitmq
    healthcheck:
      test: [ "CMD", "python", "/app/scripts/gym_management_healthcheck.py" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  postgres:
    profiles: [ "api", "dependency" ]
    container_name: domegym.postgres
    image: "postgres:16-alpine"
    hostname: domegym.postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "${GYM_MANAGEMENT_DATABASE__PORT}:5432"
    networks:
      - domegym.network
    environment:
      POSTGRES_PASSWORD: $GYM_MANAGEMENT_DATABASE__USER__PASSWORD
      POSTGRES_USER: ${GYM_MANAGEMENT_DATABASE__USER__NAME}
      POSTGRES_DB: ${GYM_MANAGEMENT_DATABASE__NAME}
    volumes:
      - domegym.postgres.data:/var/lib/postgresql/domegym.gym_mamangement:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${GYM_MANAGEMENT_DATABASE__NAME} -U ${GYM_MANAGEMENT_DATABASE__USER__NAME}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  postgres_migration:
    profiles: [ "api", "dependency" ]
    container_name: domegym.postgres_migration
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - domegym.network
    volumes:
      - ./alembic.ini:/app/alembic.ini:ro
      - ./.env:/app/.env:ro
      - ./src/gym_management/infrastructure/common/postgres/migrations:/app/src/gym_management/infrastructure/common/postgres/migrations:ro
    environment:
      GYM_MANAGEMENT_DATABASE__HOST: domegym.postgres
      GYM_MANAGEMENT_DATABASE__PORT: ${GYM_MANAGEMENT_DATABASE__PORT}
    command: ["-m", "alembic", "upgrade", "head"]

  rabbitmq:
    profiles: [ "api", "dependency" ]
    container_name: domegym.rabbitmq
    image: "rabbitmq:4.0.5-management-alpine"
    hostname: domegym.rabbitmq
    restart: unless-stopped
    expose:
      - "5672"
      - "15672"
    ports:
      - "${GYM_MANAGEMENT_RABBITMQ__PORT}:5672"
      - "${GYM_MANAGEMENT_RABBITMQ__MANAGEMENT_PORT}:15672"
    networks:
      - domegym.network
    volumes:
      - domegym.rabbitmq.data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${GYM_MANAGEMENT_RABBITMQ__USER__NAME}
      RABBITMQ_DEFAULT_PASS: ${GYM_MANAGEMENT_RABBITMQ__USER__PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  domegym.postgres.data: {}
  domegym.rabbitmq.data: {}

networks:
  domegym.network: {}
