services:
  gym_management_test:
    container_name: gym_management_test
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        PYTHON_VERSION: 3.11.10
        POETRY_VERSION: 1.8.4
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # To access Docker from within the container
    network_mode: "host" # Enables direct access to host's network
