@subscriptionId=ef0619cc-3155-4694-9d46-6367739f99aa
@gymId=6e4d4bbb-9c4e-4c04-bda3-e4cec951378c


POST http://localhost:8000/v1/subscriptions/{{subscriptionId}}/gyms/{{gymId}}/rooms
Content-Type: application/json

{
  "name": "TestRoom"
}
