@subscriptionId=c56be447-1b47-4fc7-ad22-0bc76e9b56ba
@gymId=742861c8-db12-45bb-826c-6753e772cf52


GET http://localhost:8000/v1/subscriptions/{{subscriptionId}}/gyms/{{gymId}}
Content-Type: application/json
