@subscriptionId=72815daf-140f-44f3-96cd-6ed6a7c35b74
@gymId=3d7f1a33-23e3-4e7f-92d4-e9301778f514


GET http://localhost:8000/v1/subscriptions/{{subscriptionId}}/gyms/{{gymId}}
Content-Type: application/json
