@subscriptionId=0ab13b6f-fc1c-49f7-8577-6b31333f7acb
@gymId=c9f00ffa-33dc-4d63-8197-8dbf5117319b


GET http://localhost:8000/v1/subscriptions/{{subscriptionId}}/gyms/{{gymId}}
Content-Type: application/json
