rabbitmq:
  user:
    name: "placeholder"
    password: "placeholder"
  host: "localhost"
  port: 5672
  management_port: 15672
  queues:
    - queue_name: "domain_events"
      exchange_name: "domain_events"
      routing_key: "domain_events"
