name: Code quality check
on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


env:
  TEST_DOCKERFILE_NAME: "Dockerfile.test"
  TEST_IMAGE_NAME: "domegym-test"

jobs:
  linting-source-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: |
          make lint-docker

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')
          sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build test image
        run: |
          make build-test

      - name: Tests
        run: |
          docker-compose \
            -f docker-compose.test.yaml \
            --env-file .env.test \
            --profile runner \
            run --rm -e ENV=test -v $(pwd)/coverage:/app/coverage test

      - name: Add coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage/coverage.xml
          coverage-path-prefix: src/
