name: Code quality check
on:
  workflow_dispatch: {}
  workflow_call: {}
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


env:
  TEST_DOCKERFILE_NAME: "Dockerfile.test"
  TEST_IMAGE_NAME: "domegym-test"

jobs:
  linting-source-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: KengoTODA/actions-setup-docker-compose@v1

      - name: Lint
        run: |
          make lint-docker

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build test image
        run: |
          docker-compose -f docker-compose.test.yaml build

      - name: Tests
        run: |
          docker-compose -f docker-compose.test.yaml run -e ENV=test -v $(pwd)/coverage:/app/coverage --rm gym_management_test make test

      - name: Add coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage/coverage.xml
          coverage-path-prefix: src/
